<?php
/**
 * Created by PhpStorm.
 * User: shark.zhang
 * Date: 2017/6/26 026
 * Time: 14:40
 */

echo 'PHP_VERSION = ' . PHP_VERSION . PHP_EOL;
echo 'PHP_MAJOR_VERSION = ' . PHP_MAJOR_VERSION . PHP_EOL;
echo 'PHP_MINOR_VERSION = ' . PHP_MINOR_VERSION . PHP_EOL;
echo 'PHP_RELEASE_VERSION = ' . PHP_RELEASE_VERSION . PHP_EOL;
echo 'PHP_VERSION_ID = ' . PHP_VERSION_ID . PHP_EOL;
echo 'PATH_SEPARATOR = ' . PATH_SEPARATOR . PHP_EOL;